AWSTemplateFormatVersion: 2010-09-09

Description: IAM Resources template for KOPS K8s deployment

Parameters:
  stackName:
    Description: Name of the stack to distinguish it from other stacks
    Type: String

  kopsGroupName:
    Description: Name of the KOPS group
    Type: String
    Default: eddy

  kopsUserName:
    Description: Name of the KOPS user
    Type: String
    Default: eddy

Resources:
  kopsGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Join [ "", [ "kops.", !Ref stackName, ".", !Ref kopsGroupName, ".group@", !Ref "AWS::Region" ]]
      ManagedPolicyArns:
       - "arn:aws:iam::aws:policy/AmazonEC2FullAccess"
       - "arn:aws:iam::aws:policy/IAMFullAccess"
       - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
       - "arn:aws:iam::aws:policy/AmazonVPCFullAccess"
       - "arn:aws:iam::aws:policy/AmazonRoute53FullAccess"

  kopsUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Join [ "", [ "kops.", !Ref stackName, ".", !Ref kopsUserName, ".user@", !Ref "AWS::Region" ]]
      Groups:
       - !Ref kopsGroup

  kopsUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref kopsUser

Outputs:
  kopsUserAccessKey:
    Description: Access key for the user
    Value: !Ref kopsUserAccessKey
    Export:
      Name: !Join [ "-", [ !Ref stackName, "kopsUserAccessKey" ]]

  kopsUserSecretKey:
    Description: Secret key for the user
    Value: !GetAtt kopsUserAccessKey.SecretAccessKey
    Export:
      Name: !Join [ "-", [ !Ref stackName, "kopsUserSecretKey" ]]
