apiVersion: v1
kind: Service
metadata:
  name: external-service
spec:
  type: ExternalName
  externalName: api.somecompany.com
  ports:
  - port: 80

# Once the service is created, client can connect to external-service.default.svc.cluster.local