apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubia
spec:
  tls:
  - hosts:
    - minikube.eddy.com
    secretName: tls-secret
  rules:
  - host: minikube.eddy.com
    http:
      paths:
      - path: /test
        backend:
          serviceName: kubia-nodeport
          servicePort: 80