apiVersion: v1
kind: Service
metadata:
  name: kubia-headless
spec:
# Setting the clusterIP = None will mean all the backing pod IPs are returned. This is called creating a headless service.
  clusterIP: None
  ports:
  - port: 80
    targetPort: http
  selector:
    app: kubia