apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia
spec:
  replicas: 3
# Not specifying a selector will make k8s extract the selector from the template automatically. I've included the below simply for completeness
#  selector:
#    app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
        - name: kubia
          image: luksa/kubia
          ports:
          - containerPort: 8080