apiVersion: v1
kind: Service
metadata:
  name: kubia-nodeport
spec:
  type: NodePort
  ports:
# This is the port of the service's internal cluster IP
  - port: 80
# The target port of the backing pods
    targetPort: 8080
# The service will be accessible through each node on this port
    nodePort: 30123
  selector:
    app: kubia
    enabled: "true"