apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kubia
spec:
  replicas: 3
  template:
    metadata:
      name: kubia
      labels:
        app: kubia
    spec:
      containers:
        - image: luksa/kubia:v1
          name: nodejs
          resources:
            limits: { memory: "150Mi", cpu: "100m" }
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
---
apiVersion: v1
kind: Service
metadata:
  name: kubia
spec:
  type: LoadBalancer
  selector:
    app: kubia
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubia-ingress
spec:
  tls:
    - hosts: [learn-k8s.kuber.host]
      secretName: learn-k8s-kuber-host-tls
  rules:
  - host: learn-k8s.kuber.host
    http:
      paths:
      - path: /
        backend:
          serviceName: kubia
          servicePort: 80
