apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test_ingress
spec:
  rules:
  - host: my.test.hostname.com
    http:
      paths:
      - path: /test
        backend:
          serviceName: whatever-nodeport
          servicePort: 80
