apiVersion: v1
kind: Pod
metadata:
  name: my-pod-name
  namespace: my-namespace
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["bin/sh","-c","while true; do sleep 5; done"]
